### ISSUE TITLE
Bans Don't End

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#162]
<s>I created a test ban a while ago that would last only 1 day but after more then a week it still says that I'm banned.</s>

whoops this is to do with me updating an old version of saguaro, I will enable debug soon.

**Comment by Apogate** [comment]
> He who knows when he has updated and when he has not will know victory. 
>  Sun Tzu, 2044

**Comment by Apogate** [comment]
Going to close and resolve. If you have any new developments, let me know here

**Comment by Yushe** [comment]
@Apogate 
This is what I got from debug:
<code>
Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/html/r/_core/mysql/mysql.php on line 13

Fatal error: Call to undefined function fetch_row() in /var/www/html/r/_core/regist/regist.php on line 63</code>

**Comment by RePod** [comment]
Keep in mind the latest commit on master is [broken](https://github.com/spootTheLousy/saguaro/blob/master/_core/regist/regist.php#L63) because Apogate did it in bulk.

Either use the [PR master](https://github.com/spootTheLousy/saguaro/archive/Convert-SaguaroQL.zip) which has been fixed or an older commit.
