### ISSUE TITLE
Regist cleanup

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#211]
After merging regist, some things broke:
- [x] You can post without images
  - You cannot post replies without an image. you can still post OPs without images
- [x] Regist allows posting to dead threads, resulting in orphaned posts that don't appear in the indexes, but remain in the database.
- [x] If two images are posted at once, only the first appears. If one image is posted, it doesn't appear. Regist doesn't seem to be processing the images either

The report button still doesn't work
~~catalog link in reply mode is broken~~

**Comment by RePod** [comment]
Stickies might be due to how bump order is detected during page generation.
Do stickies work in the Catalog, which actually sorts out stickies?

**Comment by Apogate** [comment]
~~Stickies do work in the catalog, but the formatting is broken. I'll see what your code does and push the fix~~

Update: i do not understand how catalog's space magic works

**Comment by RePod** [comment]
While this isn't the complete answer, this SQL query would return OPs sorted by stickies first then regular bump order (based on the `last` column).

`SELECT * FROM `imgboard` WHERE `resto` = 0 ORDER BY sticky DESC, last DESC`

There are two problems with this:
- We're currently using Log instead of querying directly.
  - Based on how we can affect Log's caching we might not need to change much.
- Stickies can still fight with each other and bumping.
  - Better than not having stickies work at all for the time being.

**Comment by RePod** [comment]
Stickies working a bit more as of dd63925102ca180db14f3fa3e392f7bca5be2393.

The most basic way to prevent sticky fighting _currently_ would be to infinitely increase the sticky column's amount. However, that's obviously a bad idea.

This is a real blanket query as opposed to how Catalog determined stickies so the fine tuning is difficult. It'd be great to only sort non-stickies by their `last` column. Fortunately, due to this change (of handling true thread order in Log's caching) Catalog's sticky determining code can be removed.

**Comment by RePod** [comment]
As of 5868a237639f9ec0ae35f2015e29d3c5c9740e5c, stickies (and regular threads) generate as expected.

Specifically as of this commit though, sticky order is by all definitions predetermined. First, all rows that are OPs are sorted by sticky status descending (true -> false) then all non-stickies are actually sorted by their `last` column descending. Therefore, sticky order is determined purely by their original ordering (so older stickies are priority).

**Comment by RePod** [comment]
Status.

**Comment by RePod** [comment]
>Slightly improved
>Goes from Minor to Major

As for fixing OPs without images, [regist/regist.php#L171](https://github.com/spootTheLousy/saguaro/blob/master/_core/regist/regist.php#L171) is where the check is.

**Comment by RePod** [comment]
Status.

**Comment by Apogate** [comment]
updating as i find them

**Comment by Apogate** [comment]
everything here has been resolved, minus report button which is a JS thing im gonna look at separately
