### ISSUE TITLE
Remove/rewrite license-unfriendly code

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#212]
Some pieces of code remain from license-unfriendly sources (futallaby) which prevent saguaro from being able to be licensed properly:
- **core/log/log.php**
  - [ ] _update_cache()_
  - [ ] _print_page()_ - pretty generic. Don't think there are many other ways to do this.
- [x] Reports popup
- [ ] Image thumbnailing (**/regist/image.php etc.**)
- [ ] **delete.php**
- [ ] **rebuild.php**
- [x] mobile.css

**Comment by RePod** [comment]
I still don't know how Rebuild works, other than it played a part in the old Regist for Log.

**Comment by Apogate** [comment]
`CACHE_TTL` is supposed to be an integer in the config. When a post was made with Old regist/log, PHP's [touch](http://php.net/manual/en/function.touch.php) method was used to see the last time some specific file we don't have right now was touched. On high traffic boards, If the last timestamp that file was touched was less than the `CACHE_TTL` value, the post was inserted into the rebuild queue instead of actually updating the thread/index HTML, and this was done until the `CACHE_TTL` limit was exceeded. It was a ghetto way of doing updates in bulk in order to save disk I/O. From my understanding, **rebuild.php** just jams every OP into the rebuildqueue and manually rebuilds every HTML page for every thread by running through the entire queue.

From what i see on 8ch, high volume boards and the constant page rebuilding is an issue most scripts have, tinyboard being one of them.

Saguaro will become the ultimate life form

**Comment by RePod** [comment]
Doesn't exactly describe the problem though. I can see in a high-traffic situation the actual problem being a lot of clashing information because it can't keep up.

However, while I haven't looked into it, I assume 4ch (based on my understanding) has the right approach. It requires a lot less resources to generate a JSON response than to generate an entire page. Couple this response with templates and a front-end javascript file to merge the two and 99% of the resource usage is placed on the client.

There are several examples of this happening, such as 4ch's thread updater and quote linking system which both work dynamically.

Our API is off to a good start, but could definitely be made more efficient. Would help to remove mobile code first so we can apply client-side templates first and expand later.

As for preserving disk life, that's not entirely our responsibility but we can do our best.

**Comment by Apogate** [comment]
>It requires a lot less resources to generate a JSON response then to generate an entire page. 

I see now, I guess it makes senses why they have such an investment in their API, as it spits out things for the catalog, every thread and every page on a board.
