### ISSUE TITLE
SQL Rewrite

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#254]
Gonna document every SQL query for the upcoming switch. Hooray. 🔫 
This is a count of every file in the repo that executes queries on the database. 

## _core/regist:
- [x] regist.php (7)
- [x] inc/process/upload.php (11)
## _core/delete:
- [x] delete/delete.php (25)
## _core/general:
- [x] resredir.php (3)
- [x] global_functions.php (1)
## _core/log:
- [x] log.php (8)
- [x] rebuild.php (7)

Roll out
---
 - [ ] Rename `$mysql` (currently discussing)
 - [x] Fix dangerous uses of `list()` and `extract()`, *highest priority to MySQL reads/writes*
   - Especially if a column rearrangement could cause problems, or if it may be redundant (implement better).
   - Redundant example: [_core/general/resredir.php](https://github.com/saguaroib/saguaro/blob/c1a6d515b98a26853c80cfe8a51d6eb88b9b099a/_core/general/resredir.php#L17)
   - Fine (could be better) example: [Tripcode.php](https://github.com/saguaroib/saguaro/blob/c1a6d515b98a26853c80cfe8a51d6eb88b9b099a/_core/regist/inc/tripcode.php#L18) (intended, doesn't involve SQL)
 - [x] Start the switch over to ~~MySQLi~~ PDO

**Comment by RePod** [comment]
>Switching from something apogate likes to something repod likes

Older and crippled software libraries/dependencies?

We're already using PHP and MySQL in general. Not doing us any favors.

**Comment by Apogate** [comment]
its just a prank bro

**Comment by RePod** [comment]
While we're doing this we should clean up the code in these areas where it's obvious to do so.

[For example](https://github.com/saguaroib/saguaro/blob/c1a6d515b98a26853c80cfe8a51d6eb88b9b099a/_core/general/resredir.php#L17), using the `list()` function on a SQL query result row.
`$mysql->fetch_assoc()` at least to skip `list()` entirely and not pollute the scope ourselves for no raisin.
In this specific case, most likely `$mysql->fetch_assoc(row)['max']`.

---

Also I have little faith in my MySQLi abstraction class. I believe I was a little out of touch when trying to implement both and also maintain the ability to intercept them.

So instead of using its re-implemented functions (which were mostly for redundancy and offloading some logic but was never used), `$mysql->connection` contains the vanilla instance. Therefore `$mysql->fetch_assoc()` would be `$mysql->connection->fetch_assoc()`.

**Comment by RePod** [comment]
Writes, Regist specifically, should also be moved to prepared statements as soon as possible (following the change to MySQLi).

Currently Regist has a [dedicated function to prepare for the write](https://github.com/saguaroib/saguaro/blob/6432214bcf6cc68a7f946ba8303c9b5d1f3e6463/_core/regist/regist.php#L127) which does a good job at intercepting the pairs of information about to be written.

It is used once for the actual post information and individually for each included file. It returns an array containing a comma-separated list of the "keys" (columns) and "vals" (values) ready to be used inline with a query.

I'm not sure if we can *dynamically* generate prepared statements, and we're handling a "lot" of data to begin with. Worst case scenario we'll have to manually update prepare statements as needed instead of it "just working" at all times. Beyond that, we might need to different setups to handle posts and their files.

---

Worth noting, the general flow of Regist's write is:
 - Write out post information without files (`media` column) to **SQLLOG**
 - Query `select last_insert_id()` to obtain the created post's number *($final)* ***(most important part)***
 - Write out each individual file's information to **SQLMEDIA** and set their `parent` as *$final*
   - Cache each one to a temporary object *($items)* as well.
 - Convert *$items* to JSON and write back to *$final*'s `media` column in **SQLLOG**

Because we do it in this order we end up doubling the amount of data written by files. The solution goes both ways:
 - Don't write back to **SQLLOG**, always reverse lookup (my preference, more but less bulkier reads)
 - Don't write to **SQLMEDIA** (Apogate's preference, less but more bulkier reads)
   - Also difficult to just determine if a post *has* media. We'd have to pull the entire column or check **SQLMEDIA**

Prepared statements might ease some of the burden of successive *writes* to **SQLMEDIA** but otherwise there is no cut and dry solution to the overhead.

**Comment by Apogate** [comment]
it has begun #255

**Comment by Apogate** [comment]
it is finished
