### ISSUE TITLE
Transparent image thumbnails have a black background

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#35]
Transparent PNG/GIF thumbnails don't maintain their transparent background.

**Comment by RePod** [comment]
Is this related to _gif2png_?

What color background is it getting, black or white?

There's very little reason to put in the effort to maintain transparency on a thumbnail but it's definitely possible (at least for PNG).

It would also require storing it in a format that supports transparency which may result in varying file sizes.

---

Unless there's some other issue, this seems to be the [intended behavior](//github.com/spootTheLousy/saguaro/blob/4c63b687c69eb495bf0f7749340507e2dca5d0ef/imgboard.php#L2089-L2090) but the transparency is not being preserved. Probably due to being saved in a [format that does not support transparency](//github.com/spootTheLousy/saguaro/blob/4c63b687c69eb495bf0f7749340507e2dca5d0ef/imgboard.php#L2096-L2097).

**Comment by Apogate** [comment]
He*k yeah this mofo can be closed as of 36587637741600f5e07bfad335ae95d24f0499c4

Resolved
