### ISSUE TITLE
Security fix: Tripcode.php and friends

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#73]
Review all **_/_core/_ **\* files to make sure they cannot run just by visiting the web path to the file

**Comment by RePod** [comment]
Specifically anything not already converted to classes (_regist_), as those already converted need to be included, initialized, and called to do anything.

_regist/regist.php_, not wrapped in a class or function, in particular lucks out when run alone because a function currently only in _imgboard.php_ is not available, among other things.

_regist/tripcode.php_, unwrapped, could potentially reveal the salt file's location or contents. However without the config loaded it would fail anyway.

**Comment by RePod** [comment]
Probably less of a concern now.

The main things that ~~needed to be dealt with~~ 1f7ff8a36671746573c6d020fb765fd1b2d04ed4 are: 
- **[$_GET](https://github.com/spootTheLousy/saguaro/search?utf8=%E2%9C%93&q=_GET&type=Code)** Used in _extract()_.
- **[$_POST](https://github.com/spootTheLousy/saguaro/search?utf8=%E2%9C%93&q=_POST&type=Code)** Used in _extract()_.
- **$_REQUEST** None as of f73f68542bba6336ceb78a5af4e54400a780ae68.

A majority of the code has been converted to classes which will not execute on their own (exception being [Captcha](https://github.com/spootTheLousy/saguaro/blob/master/_core/general/captcha.php)).

The rest of the code left unconverted work primarily as pass-throughs to modify the current scope that loaded them, usually requiring preexisting variables or functions not available. If they somehow don't end up having a fatal error, they will still do nothing (because they previously were expected to work in a specific scope).

If anything, security has been improving.

**Comment by Apogate** [comment]
Since important functions have been class-ified, this can be closed. I'll revisit this later when we have less important things to work on.
